# Generated by Django 4.2 on 2026-03-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('dob', models.DateField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Prefer not to say', 'Not')], max_length=17, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('phone_num', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
                ('Specialization', models.CharField(max_length=30, null=True)),
                ('phone_num', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Qualification', models.CharField(max_length=30, null=True)),
                ('Year_ofExp', models.CharField(max_length=20, null=True)),
                ('total_view', models.IntegerField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Date', models.DateField(max_length=10, null=True)),
                ('tims_slot', models.CharField(choices=[('9:00 AM', '9am'), ('10:00 AM', '10am'), ('11:00 AM', '11am'), ('4:00 PM', '4pm'), ('5:00 PM', '5pm'), ('6:00 PM', '6pm')], max_length=10, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
