# Generated by Django 4.2 on 2026-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
