# Generated by Django 4.2 on 2026-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[{'Male', 'M'}, {'F', 'Female'}, {'Not', 'Prefer not to say'}], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
