# Generated by Django 4.2 on 2026-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_address_user_dob_user_gender_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[{'M', 'Male'}, {'F', 'Female'}, {'Prefer not to say', 'Not'}], max_length=17, null=True),
        ),
    ]
