# Generated by Django 4.2 on 2026-03-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_booking_last_login_remove_booking_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tims_slot',
            new_name='time_slot',
        ),
    ]
