# Generated by Django 4.2 on 2026-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_tims_slot_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
