# Generated by Django 4.2 on 2026-04-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='total_view',
            field=models.IntegerField(null=True),
        ),
    ]
