# Generated by Django 4.2 on 2026-03-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='total_view',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Prefer not to say', 'Not')], max_length=17, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Date', models.DateField(max_length=10, null=True)),
                ('tims_slot', models.CharField(choices=[('9:00 AM', '9am'), ('10:00 AM', '10am'), ('11:00 AM', '11am'), ('4:00 PM', '4pm'), ('5:00 PM', '5pm'), ('6:00 PM', '6pm')], max_length=10, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
